# Generated by Django 3.2.16 on 2023-01-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0003_cartmodel_productdisplaymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartmodel',
        ),
    ]
