# Generated by Django 3.2.16 on 2023-02-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniapp', '0005_cartmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shopmodel',
        ),
    ]
